List stateList=[
        "andamanAndNicobarIslands",
        "andhraPradesh",
        "arunachalPradesh",
        "assam",
        "bihar",
        "chandigarh",
        'delhi',
        "dadraAndNagarHaveliAndDamanAndDiu",
        "goa",
        "gujarat",
        "himachalPradesh",
        "haryana",
        "jharkhand",
        "jammuAndKashmir",
         "karnataka",
        "kerala",
        "ladakh",  
        "lakshadweep",
        "maharashtra",
        "meghalaya",
          "manipur",
          "madhyaPradesh",
        "mizoram",
        "nagaland",
      "odisha",
        "punjab", 
        "puducherry",
        "rajasthan",
        "sikkim",
        "telangana",
        "tamilNadu",
        "tripura",
        "uttarPradesh",
          "uttarakhand",
        "westBengal",
    ];
                
              
 
                        
                                
